### ISSUE TITLE
Image with XOrg packages installed

### ISSUE THREAD

**Issue by petems** [tmatilai/packer-openbsd#12]
I'm a bit of a noob when it comes to OpenBSD, but I'm trying to help with a Java app so I've been using these Vagrant boxes to check.

However, when I try to install the jre I get the following:

```
pkg_add -I jre
quirks-2.9 signed on 2014-07-31T22:37:55Z
Can't install jre-1.7.0.55p1v0 because of libraries
|library X11.16.0 not found
| not found anywhere
|library Xext.13.0 not found
| not found anywhere
|library Xi.12.1 not found
| not found anywhere
|library Xrender.6.0 not found
| not found anywhere
|library Xtst.11.0 not found
| not found anywhere
|library freetype.22.0 not found
| not found anywhere
Direct dependencies for jre-1.7.0.55p1v0 resolve to libiconv-1.14p1
Full dependency tree is libiconv-1.14p1
```

From my understanding, it's because the XOrg libaries aren't installed, and these cannot be installed by ports, they have to be installed from the iso.

Is there a way to add a new packer image where you can choose to install the X libraries?

**Comment by petems** [comment]
From my understanding, it would be adding this to the provisioner:

"Do you expect to run the X Window System? = yes<enter>",

**Comment by zigg** [comment]
That question sets the kernel aperture for the X display.  You don't need it unless you're going to actually be running a desktop on the VM's display (and maybe not even then—I've never tried it.)

What you would need to change is `Set name(s)`—they shouldn't subtract the X packages anymore (remove `-x*.tgz`).

**Comment by petems** [comment]
@zigg Ah, I see. Awesome, I'll give that a go! 

I'm assuming you dont include them because it would make the Vagrant boxes a lot larger?

**Comment by zigg** [comment]
Honestly, I didn't make that decision 😊  It's been that way for awhile.

**Comment by petems** [comment]
Yep changing that fixed it! :+1: Thanks :smile:

**Comment by tmatilai** [comment]
> I'm assuming you dont include them because it would make the Vagrant boxes a lot larger?

Yes, exactly. In most of the cases you don't need X on a server. Isn't there any "headless" version of the JRE available?

**Comment by petems** [comment]
@tmatilai I'm not sure, I'm just using the port of JRE that comes with the standard ports. If there's another port that doesn't need the X packages that would be awesome, saves me having to build my own box :)
