### ISSUE TITLE
5.7 box on atlas is failing to download with "missing metadata.json" message

### ISSUE THREAD

**Issue by joemiller** [tmatilai/packer-openbsd#13]
I am trying to use the 5.7 on atlas but getting the following message:

```
$ vagrant init tmatilai/openbsd-5.7
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'tmatilai/openbsd-5.7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'tmatilai/openbsd-5.7'
    default: URL: https://atlas.hashicorp.com/tmatilai/openbsd-5.7
==> default: Adding box 'tmatilai/openbsd-5.7' (v1.0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/tmatilai/boxes/openbsd-5.7/versions/1.0.0/providers/virtualbox.box
The "metadata.json" file for the box 'tmatilai/openbsd-5.7' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

http://docs.vagrantup.com/v2/boxes/format.html
```

vagrant 1.7.4

**Comment by tmatilai** [comment]
Damn, I got a report for that but dropped the ball. The metadata.json should definitely be included into the box, so it might have been a Packer issue. I'll try to take closer look soon.

I think you should be able to get around the issue now with something like
```sh
vagrant box add tmatilai/openbsd-5.7 --provider virtualbox
```

**Comment by jpooler** [comment]
I tried specifying the provider and still hit the issue @joemiller mentioned as well. I was trying for the 5.6 box, but also hit this for the 5.7 box.

 vagrant box add tmatilai/openbsd-5.6 --provider virtualbox
==> box: Loading metadata for box 'tmatilai/openbsd-5.6'
    box: URL: https://atlas.hashicorp.com/tmatilai/openbsd-5.6
==> box: Adding box 'tmatilai/openbsd-5.6' (v1.1.0) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/tmatilai/boxes/openbsd-5.6/versions/1.1.0/providers/virtualbox.box
The "metadata.json" file for the box 'tmatilai/openbsd-5.6' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

http://docs.vagrantup.com/v2/boxes/format.html

**Comment by joemiller** [comment]
I have a box up at joemiller/openbsd-5.7-amd64 on atlas right now if you
need something fast. I don't have any 5.6 builds up though.. Small tweaks
to the json but largely the same as Teemu's images. I will push them up to
GH in the next few days.

Of note, I included the bsd.mp kernel in the image so you can use SMP.

**Comment by tmatilai** [comment]
Well, this seems like a Hashicorp Atlas issue now, as the built boxes *do* include metadata.json. Earlier I built and hosted the actual boxes myself in S3, but for these releases I chose to use Atlas to do all the hard work. I'll try to build the boxes again to see if the issue persists.

**Comment by tmatilai** [comment]
OK, found the issue: mitchellh/packer#2090
New builds are now in the pipe.

**Comment by tmatilai** [comment]
So this should be fixed now. Please tell me if you still hit into problems.
