### ISSUE TITLE
Contribute box definitions back to Bento?

### ISSUE THREAD

**Issue by joemiller** [tmatilai/packer-openbsd#14]
I am working on improving OpenBSD support in Chef and having official bento boxes for OpenBSD is something that I think will help with things like getting official omnibus builds into the pipeline. Would you consider contributing your box defs (at least 5.7) back to the official Bento git repo?

Or would you mind if I used your packer defs as a basis for contributing back to Bento instead?

thanks

**Comment by tmatilai** [comment]
Hi Joe,

I already tried to get these into Bento a while ago (chef/bento#166). This repo was finally created because they didn't want them at the time. I would be more than happy to pass the maintenance if you want to ask again. =)

**Comment by joemiller** [comment]
Thanks, I read the thread. Although I've been making some progress on
bumping the support level of OpenBSD in Chef, I'm not sure if Bento would
accept the box yet. I looked at boxcutter which takes a different approach
with a repo-per-operating-system. And creating a new repo looks like a bit
more work than I want to bite off at the moment =) Going to think about
what to do next. I might send a PR with some minor updates and try to keep
the work on this repo until a later time.

**Comment by tmatilai** [comment]
I'm going to close this issue, but please keep me informed if you get into contact with Chef Inc/Bento.

And PRs are of course highly appreciated. Send a good one and I'll add you as a contributor. =)
