### ISSUE TITLE
OpenBSD 5.8 virtualbox-iso builder failing to shutdown

### ISSUE THREAD

**Issue by aalmazan** [tmatilai/packer-openbsd#17]
When attempting to build a virtualbox box, the shutdown command does not seem to be sending properly. Error log below: 

```
$ packer build -only=virtualbox-iso openbsd-5.8-amd64.json

==> virtualbox-iso: Gracefully halting virtual machine...
==> virtualbox-iso: Failed to send shutdown command: EOF
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Failed to send shutdown command: EOF
```

A workaround I found is to change line 56 in `openbsd-5.8-{amd64,i386}.json`:
```
- "shutdown_command": "/sbin/halt -p",
+ "shutdown_command": "/sbin/shutdown -h now",
```

After the system halts and disks sync, I manually power off the VM. Is there something preventing `/sbin/halt -p` from working? 

EDIT: 
System details:
* Xubuntu 15.04
* VirtualBox 5.0.8 r103449

**Comment by zigg** [comment]
I just built a 5.8 box this morning with VirtualBox and didn't experience this. I'm using VBox 5.0.10 and OS X, but I can't imagine that either would make a difference. Is there anything else happening in your environment I may be missing?

**Comment by aalmazan** [comment]
Sorry for the delay, tried it again multiple times but it is still showing the same output as before. I am also using the latest VirtualBox available: `Version 5.0.10 r104061`. This may be a Linux/Ubuntu-only issue -- will test again on different Linux distros.

**Comment by zigg** [comment]
I wonder if changing the `shutdown_command` to something like `sleep 2 && /sbin/halt -p` might solve the problem. Maybe the `Failed to send shutdown command: EOF` command is indicating that the VM is shutting down before Packer receives acknowledgement that the command was sent.

I would definitely prefer to not have a manual shutdown if we can avoid it.

**Comment by zigg** [comment]
Also, @aalmazan, if you could try pulling the latest `master` and see if you still have an issue, that'd be great. I've tightened up a few things recently—not specifically around shutting down, but it's worth a shot.

**Comment by zigg** [comment]
Another one to try if the my other suggested command doesn't work: `nohup halt -p && exit`. Just thinking through how this could fail…

**Comment by aalmazan** [comment]
Synced the newest changes on the upstream master and all seems well. Closing this issue -- may have all been my fault due to an outdated repo.

**Comment by zigg** [comment]
Thanks, @aalmazan! If you have any further trouble, feel free to reopen—this ticket got me wondering about the potential for a shutdown/ssh race condition, and if it rears its head again, it'd be nice to find a solution for it.
