### ISSUE TITLE
Tag old releases

### ISSUE THREAD

**Issue by zigg** [tmatilai/packer-openbsd#19]
I wanted to go ahead and implement the OpenBSD version management scheme we proposed in PR #15, tagging then purging old templates, keeping the two latest around.

To prepare for this, I've been trying to figure out [what's on Atlas](https://atlas.hashicorp.com/boxes/search?q=tmatilai%2Fopenbsd) vs. what's in our repo.  Here's the state I think we're in:

OpenBSD | Atlas | Tag | Notes
------- | ----- | --- | -----
5.4 | 1.0.0 | None | It looks like we've added QEMU and Ansible support since the last Atlas release ([history](https://github.com/tmatilai/packer-openbsd/commits/master/openbsd-5.4-amd64.json)). Should we tag 1.1.0 and build a new Atlas box?
5.5 | 1.0.0 | 1.0.0 | Same story as 5.4 ([history](https://github.com/tmatilai/packer-openbsd/commits/master/openbsd-5.5-amd64.json)).
5.6 | 1.1.1 | 1.1.1 | Appears up-to-date ([history](https://github.com/tmatilai/packer-openbsd/commits/master/openbsd-5.6-amd64.json)).
5.7 | 1.0.2 | 1.0.2 | Appears up-to-date ([history](https://github.com/tmatilai/packer-openbsd/commits/master/openbsd-5.7-amd64.json)).
5.8 | None | None | We need to tag and build this box yet.

I'd like to take this as a first step before merging the 5.8 script into the main set of scripts. I also have a number of other cleanups in mind, but we can discuss them next. 😊

**Comment by zigg** [comment]
@tmatilai, since this affects box builds, do you have any input?

**Comment by tmatilai** [comment]
Not sure if building old QEMU boxes is worth the effort. And Ansible support is not included by default.

Anyway, the 5.8 boxes really should be published, not sure how I have totally forgotten to do so. =)

So from my point of you, feel free to continue. :)
