### ISSUE TITLE
Deprecate in favor of boxcutter?

### ISSUE THREAD

**Issue by zigg** [tmatilai/packer-openbsd#25]
I sat down last night to get 6.0 going, making improvements like using [doas(1)](http://man.openbsd.org/doas.1) and branches for provisioners.

I discovered that boxcutter already has 6.0 support in place, and it already works.

Rather than duplicate effort, how would you all feel about marking this project deprecated in favor of boxcutter?

**Comment by dentarg** [comment]
Sure

Just for reference, here's a link to the repo: https://github.com/boxcutter/bsd

**Comment by zigg** [comment]
The one thing boxcutter's templates don't appear to have is provisioner support—at least not Python for Ansible.

**Comment by dentarg** [comment]
Oh, that's the one provisioner I care about... but I think I will continue my efforts over at https://github.com/twingly/boxes (when the times comes for our upgrade)

**Comment by tmatilai** [comment]
I'm fine with whatever seems like the best idea. I am not using this repo myself so sadly the motivation too keep up is reduced.

**Comment by zigg** [comment]
Yeah, I am pretty spotty myself, though I hope to get back into it as I want to move my cloud server to OpenBSD.

I think the answer to whether I continue here or move to boxcutter depends on how open they are to provisioner patches. I would also like Ansible.

I am definitely impressed with the many little improvements they have made that we don't have in this repo, like doas support and delivering install.conf via HTTP.

**Comment by carletes** [comment]
Like @tmatilai, I'm not using this repo much nowadays. I'm happy with whatever decision you take, people.

**Comment by ryanmaclean** [comment]
I still use it :)

**Comment by isido** [comment]
Boxcutter doesn't support QEMU/libvirt, so at least I'm still using this. And it seems (at least with the Ubuntu box) that boxcutter likes to install all sorts of programs, so I am happy to keep using this packer.

**Comment by ryanmaclean** [comment]
@isido - are you able to help test QEMU/libvirt output from this repo?

**Comment by isido** [comment]
@ryanmaclean In principle yes (and I have used 5.8 in QEMU), but in practise, probably not for at the moment, since I'm in process of switching machines and using macOS in the interim.

**Comment by ryanmaclean** [comment]
Shall we close this, maybe?
